config/routes.rb
Rails.application.routes.draw do
  root 'public/items#top'
  devise_for :admin, controllers: {
     sessions: 'admin/sessions'
     }
     #どこのコントローラーを引っ張ってくるかの記述
     #adminディレクトリのsessionsコントローラーを指定することが出来る
     #記述がないと、deviseディレクトリのsessionsコントローラーを引っ張ってくる

  scope module: :public do
      resource :end_users, only: [:show, :edit, :update, :destroy] #デバイスの下にあるとeditに飛ばしたとき、deviseのeditが読み込まれてしまうため,resourceを上に書く。idを付与しないのでresourceである
     devise_for :end_users, controllers: {
        sessions: 'public/end_users/sessions',
        registrations: 'public/end_users/registrations'
     }
     # post 'orders/information' => 'orders#information', as: "information"
     delete 'cart_items/destroy_all' => 'cart_items#destroy_all',as: "destroy_all"
     resources :cart_items, only: [:index, :update, :destroy, :create] do
       post 'orders/information' => 'orders#information', as: "information"
       get 'orders/completed' => 'orders#completed', as: "completed"
       resources :orders, only: [:new, :create, :index]
     end
     resources :items, only: [:index, :show]
     resources :addresses, only: [:index, :edit, :create, :update, :destroy]
   #   delete 'cart_items/destroy_all' => 'cart_items#destroy_all',as: "destroy_all" # resourceより後にあるので、viewを作ってないと,resourceのdestroyが先に読み込まれる
   # urlを指定するか指定しないかの違いは、resourceで先に読み込まれるか,viewを作るか
   # cart_itemsで指定するなら何もしなくてよいけど、
   # cart_items/destroy_allで指定するならば、viewファイルと、resouceより上に書かないといけない(cart_items/:idのidとしてdestroy_allが読み込まれてしまう)
     get 'end_users/confirm' => 'end_users#confirm',as: "confirm"                  #resourcesの中に存在しないので、自分で設定する必要がある。
     patch 'end_users/withdrawal' => 'end_users#withdrawal',as: "withdrawal"
  end
  namespace :admin do
     get 'top' => 'top#top'
     resources :genres, only: [:index, :create, :edit, :update]
     resources :end_users, only: [:index, :create, :edit, :update]
     resources :items, only: [:index, :new, :create, :show, :edit, :update]
     resources :orders, only: [:index, :show, :update]
     resources :order_details, only: [:update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :end_user, -> {with_deleted} #親のクラスは削除したものも取ってくるように設定
	has_many :order_details

	validates :payment_methods, presence: true

	enum payment_methods: { credit: 0, bank: 1 }
	enum order_status: {waiting: 0, confilm: 1, producting: 2, before_shipping: 3, done_shipping: 4}
	

	def order_count
		sum = 0
		self.order_details.each do |detail| # selfはorderモデルを表しているため、order.allと同じ意味？
			# selfは使う先(view)を利用している
			sum += detail.quanitity
		end
		return sum
	end

	def order_prace
		sum = 0
		self.order_details.each do |order_detail|
			sum += order_detail.unit_price * order_detail.quanitity
		end 
		return sum
	end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
	def index
		 @orders = Order.all
	end

	def show
		@order = Order.find(params[:id])
		@change_order = Order.new
		@change_item = CartItem.all
	end

	def update
		@order = Order.find(params[:id]) #送られてきたidを受け取って、CartItemモデルのidと同じものを探す
		@order.update(order_status: params[:order][:order_status])
		if @order.order_status == "confilm"
		   @detail = OrderDetail.where(order_id: params[:id]) #送られてきたidを受け取って、CartItemモデルのidと同じものを探す
		   @detail.update(production_status: "waiting")
		 end
		# @order.update(orders_params)
		redirect_to request.referer
	end

	# private
	# def orders_params
	# params.require(:order).permit(:payment_methods, :address, :postal_code, :addressee,:end_user_id,:shipping_fee, :billing_price_sum, :order_status)
 #  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<section class="items_all">
<div class="container">
  <div class="row">
  <div class="col-xs-offset-1">
  	<strong style="margin-left: 50px;">注文履歴一覧</strong>
  </div>
  <div class="col-xs-offset-11">
    <%= link_to new_admin_item_path do %>
    <span class="glyphicon glyphicon-plus" style="font-size:30px;" aria-hidden="true"></span>
    <% end %>
  </div>
</div>
  <br>
  <div class="col-xs-11 col-xs-offset-1">
    <table class='table table-hover table-inverse'>
      <thead>
        <tr>
          <th>購入日時</th>
          <th>購入者</th>
          <th>注文個数</th>
          <th>注文ステータス</th>
        </tr>
      </thead>

      <tbody>
        <% @orders.each do |order| %>
        <%# binding.pry %>
        <tr>
          <td><%= link_to admin_order_path(order.id) do %>
                <%= order.created_at.to_s(:datetime_jp) %>
              <% end %>
          </td>
          <td><%= order.end_user.first_name %><%= order.end_user.last_name %></td>
          <td><%= order.order_count %></td>
         <%
=begin%>
 <td>
          <% @sum = 0 %> <!-- @sumに0を代入 -->
          <% order.order_details.each do |detail| %> <!-- eachで一つずつを取り出して,そのorderの1対多のorder_detailsテーブルをeachで一つずつ取り出す。 -->
           <% @sum = @sum + detail.quanitity %> <!-- @sumにorder_detailsのquanitityを代入 -->
           <% end %>
           <%= @sum %> <!-- @sumを代入 -->
         </td> 
<%
=end%>
          <td><%= order.order_status_i18n %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>


app/views/admin/orders/show.html.erb
<section class="items_all">
  <div class="container">
    <div class="row">
      <div class="col-xs-offset-1">
        <strong style="margin-left: 50px;">注文履歴詳細</strong>
      </div>
    </div>
    <div class="row">
      <div>
        <strong>購入者</strong>
        <p style="display:inline; margin-left:50px;">
          <%= link_to admin_end_users_path do %>
          <!-- 各会員の詳細画面に飛ばすために修正 -->
          <%= @order.end_user.first_name %><%= @order.end_user.last_name %>
          <% end %>
        </p>
      </div>
      <div>
        <strong>配送先</strong>
        <p style="display:inline; margin-left:50px;">
          <%= @order.postal_code + @order.address %><br>
          　　　　　　　<%= @order.addressee %>
        </p>
      </div>
      <div>
        <strong>支払い方法</strong>
        <p style="display:inline; margin-left:25px;">
          <%= @order.payment_methods_i18n %>
        </p>
      </div>
      <div>
        <%= form_with model: @change_order, url: admin_order_path(@order.id), method: :patch ,local:true do |f| %>
        <%= f.label :order_status, "注文ステータス" %>
        <%= f.select :order_status, Order.order_statuses.keys.map {|k| [I18n.t("enums.order.order_status.#{k}"), k]}, include_blank: @order.order_status_i18n %>
        <%= f.submit "更新" %>
        <% end %>
      </div>
      <br>
      <br>
      <div class="col-xs-8">
        <table class='table table-hover table-bordered table-inverse'>
          <thead>
            <tr>
              <th>商品名</th>
              <th>単価（税込）</th>
              <th>数量</th>
              <th>小計</th>
              <th>製作ステータス</th>
            </tr>
          </thead>

          <tbody>
            <% @order.order_details.each do |order_detail| %>
            <tr>
              <td>
                <%= order_detail.item.name %>
              </td>
              <td><%= (order_detail.unit_price *= 1.08).round %></td>
              <td><%= order_detail.quanitity %></td>
              <td><%= order_detail.unit_price * order_detail.quanitity  %></td>
              <td><%= form_with model: @change_item, url: admin_order_detail_path(order_detail.id), method: :patch ,local:true do |f| %>
                <!-- form_withでプルダウンを作って更新 -->
                <%= f.select :production_status, OrderDetail.production_statuses.keys.map {|k| [I18n.t("enums.order_detail.production_status.#{k}"), k]}, include_blank: order_detail.production_status_i18n %>
                <%= f.submit "更新" %>
                <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="col-xs-4">
        <div style="margin-top:60px;">
          <strong>商品合計</strong>
          <%= @order.order_prace %>円
        </div>
        <div>
          <strong>送料</strong>
          <%= @order.shipping_fee %>円
        </div>
        <div>
          <strong>請求金額合計</strong>
          <%= @order.order_prace + @order.shipping_fee %>円
        </div>
      </div>
    </div>
  </div>
</section>