config/routes.rb
Rails.application.routes.draw do
  root 'public/items#top'
  devise_for :admin, controllers: {
     sessions: 'admin/sessions'
     }
     #どこのコントローラーを引っ張ってくるかの記述
     #adminディレクトリのsessionsコントローラーを指定することが出来る
     #記述がないと、deviseディレクトリのsessionsコントローラーを引っ張ってくる

  scope module: :public do
      resource :end_users, only: [:show, :edit, :update, :destroy] #デバイスの下にあるとeditに飛ばしたとき、deviseのeditが読み込まれてしまうため,resourceを上に書く。idを付与しないのでresourceである
     devise_for :end_users, controllers: {
        sessions: 'public/end_users/sessions',
        registrations: 'public/end_users/registrations'
     }
     # post 'orders/information' => 'orders#information', as: "information"
     delete 'cart_items/destroy_all' => 'cart_items#destroy_all',as: "destroy_all"
     resources :cart_items, only: [:index, :update, :destroy, :create] do
       post 'orders/information' => 'orders#information', as: "information"
       get 'orders/completed' => 'orders#completed', as: "completed"
       resources :orders, only: [:new, :create, :index]
     end
     resources :items, only: [:index, :show]
     resources :addresses, only: [:index, :edit, :create, :update, :destroy]
   #   delete 'cart_items/destroy_all' => 'cart_items#destroy_all',as: "destroy_all" # resourceより後にあるので、viewを作ってないと,resourceのdestroyが先に読み込まれる
   # urlを指定するか指定しないかの違いは、resourceで先に読み込まれるか,viewを作るか
   # cart_itemsで指定するなら何もしなくてよいけど、
   # cart_items/destroy_allで指定するならば、viewファイルと、resouceより上に書かないといけない(cart_items/:idのidとしてdestroy_allが読み込まれてしまう)
     get 'end_users/confirm' => 'end_users#confirm',as: "confirm"                  #resourcesの中に存在しないので、自分で設定する必要がある。
     patch 'end_users/withdrawal' => 'end_users#withdrawal',as: "withdrawal"
  end
  namespace :admin do
     get 'top' => 'top#top'
     resources :genres, only: [:index, :create, :edit, :update]
     resources :end_users, only: [:index, :create, :edit, :update]
     resources :items, only: [:index, :new, :create, :show, :edit, :update]
     resources :orders, only: [:index, :show, :update]
     resources :order_details, only: [:update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
	belongs_to :end_user
	def postal_address_addressee
		self.postal_code.to_s + "　" + self.address + "　" + self.addressee 
	end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :item
	belongs_to :end_user
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  acts_as_paranoid #論理削除の際に必要

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :email, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  has_many :cart_item
  has_many :orders
  has_many :addresses
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :genre
	has_many :cart_item #cart_itemsになっていないので、コントローラで呼び出すときにcart_itemsにするとエラーが出る
	has_many :order_datails
	attachment :image
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :end_user, -> {with_deleted} #親のクラスは削除したものも取ってくるように設定
	has_many :order_details

	validates :payment_methods, presence: true

	enum payment_methods: { credit: 0, bank: 1 }
	enum order_status: {waiting: 0, confilm: 1, producting: 2, before_shipping: 3, done_shipping: 4}
	

	def order_count
		sum = 0
		self.order_details.each do |detail| # selfはorderモデルを表しているため、order.allと同じ意味？
			# selfは使う先(view)を利用している
			sum += detail.quanitity
		end
		return sum
	end

	def order_prace
		sum = 0
		self.order_details.each do |order_detail|
			sum += order_detail.unit_price * order_detail.quanitity
		end 
		return sum
	end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
	belongs_to :order
	belongs_to :item

	enum production_status: { not_start: 0, waiting: 1, start: 3, finish: 4 }
end

app/controllers/admin/end_users_controller.rb
class Admin::EndUsersController < ApplicationController
	def index
		@end_users = EndUser.with_deleted #論理削除されたデータも「含める」  削除されたデータのみを表示したい場合はModel.only_deleted
	end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
  	 @genres = Genre.all
  	 @genre = Genre.new
  end

  def create
  	 genre = Genre.new(genre_params)
  	 genre.save
  	 redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private
  def genre_params
  	 params.require(:genre).permit(:name, :is_valid)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    if params[:search].present? #もしform_withで:search情報が送られてきたら
      @items = Item.where('name LIKE ?', "%#{params[:search]}%")
      #Itemの情報からwhereでnameカラムに送られた文字と一致するものを探す
      # @items = @items.where('name LIKE ?', "%#{params[:search]}%") if params[:search].present? 一行で書くとこうなる
    else #form_withで送られなかったら
      @items = Item.all
    end
  end

  def new
    @item = Item.new
  end

  def create
    item = Item.new(item_params)
    item.save #エラー箇所？？？
    redirect_to admin_item_path(item)

  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
  end

  def update
  end

  private
  def item_params
    params.require(:item).permit(:name, :genre_id, :description, :tax_excluded_price, :image, :is_on_sale)
  end


end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
	def index
		 @orders = Order.all
	end

	def show
		@order = Order.find(params[:id])
		@change_order = Order.new
		@change_item = CartItem.all
	end

	def update
		@order = Order.find(params[:id]) #送られてきたidを受け取って、CartItemモデルのidと同じものを探す
		@order.update(order_status: params[:order][:order_status])
		if @order.order_status == "confilm"
		   @detail = OrderDetail.where(order_id: params[:id]) #送られてきたidを受け取って、CartItemモデルのidと同じものを探す
		   @detail.update(production_status: "waiting")
		 end
		# @order.update(orders_params)
		redirect_to request.referer
	end

	# private
	# def orders_params
	# params.require(:order).permit(:payment_methods, :address, :postal_code, :addressee,:end_user_id,:shipping_fee, :billing_price_sum, :order_status)
 #  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	before_action :configure_permitted_parameters, if: :devise_controller?

	def after_sign_in_path_for(resource) #resourceはモデルを表している
      case resource
      when Admin
        admin_top_path
      when EndUser
        items_path
      end
  end
    def after_sign_out_path_for(resource) #:adminをモデルとしてみている？？
       case resource
       when :admin
        new_admin_session_path
       when :end_user
        root_path
      end
    end
    protected
    def configure_permitted_parameters
	  devise_parameter_sanitizer.permit :sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :phone_number]
	end
end

app/helpers/admin/end_users_helper.rb
module Admin::EndUsersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
          <% if end_user_signed_in? %>
          <nav class="nav navbar-nav navbar-left">
            <li>
              <%=link_to "LOGO", root_path %>
            </li>
          </nav>
          <nav>
            <ul class="nav navbar-nav navbar-right">
              <li>
                <p style="color:white; margin-top: 15px; margin-right: 300px;">ようこそ<%= current_end_user.first_name %>さん!</p>
              </li>
              <li>
               <%= link_to "マイページ", end_users_path %>
              </li>
              <li>
                <%= link_to "商品一覧",items_path %>
              </li>
              <li>
                <%= link_to "カート", cart_items_path %>
              </li>
              <li>
                <%= link_to "ログアウト", destroy_end_user_session_path, method: :delete %>
              </li>
              </ul>
           </nav>
           <% elsif admin_signed_in? %>
             <nav class="nav navbar-nav navbar-left">
              <li>
                <%=link_to "LOGO", admin_top_path %>
              </li>
             </nav>
             <nav>
              <ul class="nav navbar-nav navbar-right">
              <li>
                <%= link_to "商品一覧", admin_items_path %>
              </li>
              <li>
                <%= link_to "会員一覧", admin_end_users_path  %>
              </li>
              <li>
                <%= link_to "注文履歴一覧", admin_orders_path %>
              </li>
              <li>
                <%= link_to "ジャンル一覧", admin_genres_path %>
              </li>
              <li>
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>
              </li>
              <br>
              <div class="pull-right">
              <%= form_with url: admin_items_path, method: :get, local: true do |f| %>
                <%= f.text_field :search %>
                <%= f.submit 'Search', name: nil %>
              <% end %>
            </div>
            </ul>
          </nav>
           <% else %>
             <nav class="nav navbar-nav navbar-left">
              <li>
                <%=link_to "LOGO", root_path %>
              </li>
            </nav>
            <nav>
              <ul class="nav navbar-nav navbar-right">
              <li>
                <%= link_to "商品一覧", items_path %>
              </li>
              <li>
                <%= link_to "新規登録", new_end_user_registration_path  %>
              </li>
              <li>
                <%= link_to "ログイン", new_end_user_session_path %>
              </li>
            </ul>
          <% end %>
        </nav>
      </div>
    </header>
        <br>
        <br>
    <%= yield %>
  </body>
</html>